### ISSUE TITLE
Story: Intro adventure!

### ISSUE THREAD

**Issue by NovaCrypt** [NovaCrypt/HeroicMightMGD#14]
### Roadmap

- [x] Create a new monster.
- [ ] Add new NPC of the new monster type.
- [ ] Introduce the girl in a new 'adventure'!

_Required for 1.0!_
