### ISSUE TITLE
Monster: Demonic Slime

### ISSUE THREAD

**Issue by NovaCrypt** [NovaCrypt/HeroicMightMGD#8]
### Overview

The demonic slime is a relatively simple variation on the basic blue slime. She has the same kind of attitude yet is far more powerful, her slime has also been tinted purple from all the demonic energy swirling inside her. She has a magical ability as well as Perpetua's more direct attack moves.

### Detailed Info

The demonic slime comes in with a base lvl of 15. Her stats are improved also and she has a broader moveset to the blue slimes. She is also nearly immune to most forms of damage and is only weak to holy skills. **CANNOT BE ENCOUNTERED WITHOUT THE SIGIL OF ALLURE!**

- [x] Setup monster file.
- [x] Provide basic monster details (name, desc.)
- [x] Add monster stats
- [x] Add sensitivities
- [x] Add move set
- [x] Add new item drops #9 
- [x] Alter images to suit description. #10 
- [x] Add location lists... #12 
- [x] Customise the loss scenes
- [x] Customise the move dialogues

_Due to roll out in the 0.3.0 release..._

**Comment by NovaCrypt** [comment]
In the 0.3.0 branch, this is now basically ready to add to a location. The only thing is that she currently uses the basic slime dialogue during battle. However, she is currently not added to any grimoire lists so, that's probably the next step...
